service:
  #????????? ??????????? ? ????????? ??????????
  client-certiicate-key-file-name: /mnt/MyProjects/git/quic_test_quiche4j/src/main/resources/cert.crt
  client-private-key-file-name: /mnt/MyProjects/git/quic_test_quiche4j/src/main/resources/cert.key
  client-max-datagram-size: 1350
  client-user-agent: Quiche4j
  # ??? ????? ?????? ? ?????? ???????? ??? ? ?????
  client-receiver-host: localhost
  client-receiver-port: 4433

  #????????? ??????????? ?? ????????? ???????????
  server-certiicate-key-file-name: /mnt/MyProjects/git/quic_test_quiche4j/src/main/resources/cert.crt
  server-private-key-file-name: /mnt/MyProjects/git/quic_test_quiche4j/src/main/resources/cert.key
  server-max-datagram-size: 1350
  server-header-name: server
  server-name: Quiche4j
  server-host: localhost
  server-port: 4433